// <auto-generated />
namespace JapaneseWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ver0_Levels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ver0_Levels));
        
        string IMigrationMetadata.Id
        {
            get { return "201905230025065_ver0_Levels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
